#source('http://bioconductor.org/biocLite.R')
#biocLite('SRAdb')
library(SRAdb)
srafile = getSRAdbFile()
file.info(srafile)
con = dbConnect(RSQLite::SQLite(),srafile)
getSRAfile('SRP109830',con,fileType='sra')
